provider:
  name: faas
  gateway: http://localhost:8080

functions:
  faas-stamp:
    lang: Dockerfile
    handler: ./function
    image: alexellis2/faas-stamp:0.3
  polaroid:
    lang: Dockerfile
    handler: ./polaroid
    image: alexellis2/faas-polaroid:0.1

